version: "3.7"

services:
  mariadb:
    container_name: mariadb_service
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - '.docker/mysql.cnf:/etc/mysql/conf.d/docker.cnf'
    networks:
      docker-server:
        ipv4_address: 172.29.0.2

  phpmyadmin:
    container_name: phpmyadmin_service
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - 9090:80
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_MYSQL}
      PMA_HOST: mariadb
      UPLOAD_LIMIT: '300M'
      MAX_EXECUTION_TIME: '-1'
      MEMORY_LIMIT: '-1'
    networks:
      docker-server:
        ipv4_address: 172.29.0.3

  mailhog:
    container_name: mailhog_service
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      docker-server:
        ipv4_address: 172.29.0.5

  redis:
    container_name: redis_service
    image: redis
    ports:
      - 6379:6379
    networks:
      docker-server:
        ipv4_address: 172.29.0.6

  php-fpm:
    container_name: php_fpm_service
    image: cezlab/php-8.2-fpm
    depends_on:
      - mariadb
    links:
      - mariadb
    ports:
      - 9000:9000
    volumes:
      - './:/var/www/html/'
      - '.docker/php.ini:/usr/local/etc/php/php.ini'
    networks:
      docker-server:
        ipv4_address: 172.29.0.7

  web_service:
    container_name: web_service
    image: nginx:latest
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php-fpm
    links:
      - php-fpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - './:/var/www/html/'
      - '.docker/nginx.conf:/etc/nginx/conf.d/default.conf'
    networks:
      docker-server:
        ipv4_address: 172.29.0.8

  elasticsearch:
    container_name: elasticsearch_service
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    networks:
      docker-server:
        ipv4_address: 172.29.0.9

  kibana:
    container_name: kibana_service
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    environment:
      - ELASTICSEARCH_HOSTS=http://172.29.0.9:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      docker-server:
        ipv4_address: 172.29.0.10

networks:
  docker-server:
    name: docker-server-services
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16